### ISSUE TITLE
IGDataPath creation on Windows

### ISSUE THREAD

**Issue by ghost** [danleyb2/Instagram-API#13]
On windows, the IGDataPath directory fails to be created.

In Instagram.py, it appears to be implemented like this
```python
if not os.path.isdir(self.IGDataPath):
                os.mkdir(self.IGDataPath, 0777)
```
...which throws an exception on Windows.

I fixed this with a helper method in my code:
```python
def mkdir(p):
    try:
        os.makedirs(p)
        if debug:
            print "made dir: " + p
    except OSError as exc:  # Python >2.5
        if exc.errno == errno.EEXIST and os.path.isdir(p):
            pass
        else:
            raise


def getInstagram(username, password, debug):
    p = os.path.join(os.path.dirname(InstagramAPI.__file__), "src\\data\\" + username)
    mkdir(p)
    i = InstagramAPI.Instagram(username, password, debug)
    return i
```

I haven't tested the helper method in Linux but it works in Windows now.
Please fix the IGDataPath directory creation in the library.

**Comment by PixelZerg** [comment]
NB: Installing the latest version using `pip install https://github.com/danleyb2/Instagram-API/archive/master.zip` did not help.

New stack trace:
```
File "C:\Python27\lib\site-packages\InstagramAPI\src\Instagram.py", line 319, in uploadPhoto
    return self.http.uploadPhoto(photo, caption, upload_id)
  File "C:\Python27\lib\site-packages\InstagramAPI\src\http\HttpInterface.py", line 141, in uploadPhoto
    data = self.buildBody(bodies, boundary)
  File "C:\Python27\lib\site-packages\InstagramAPI\src\http\HttpInterface.py", line 584, in buildBody
    body += ("\r\n\r\n" + b['data'] + "\r\n")
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by danleyb2** [comment]
Hello, 
Could you please show the exception stack trace, 

Using **Windows10** Python **2.7.13**
everything seems to work fine on my end except when in Python interactive shell because then it doesn't detect current file path from `os.path.realpath(__file__)`
