### ISSUE TITLE
Exeption TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by h00p** [danleyb2/Instagram-API#20]
Hello

On uploadPhoto i take exeption "list indices must be integers, not str"

in ConfigureResponse.py on line 14 u have mistake quotes

self.image_url = response['media']['image_versions2']['candidates']['0']['url']

right version is:
self.image_url = response['media']['image_versions2']['candidates'][0]['url']

**Comment by danleyb2** [comment]
Hello @h00p 

This was also an issue on the PHP code and seems to get fixed at this commit mgp25/Instagram-API@2c87a8465833c14440a39d014cdc1d72229d8518 

I'll add a TODO with your username as the author to make it something to watch out for

Thanks for the note though,
