### ISSUE TITLE
No JSON object could be decoded - i.direct_message(recipients, text)

### ISSUE THREAD

**Issue by kennychung** [danleyb2/Instagram-API#30]
I get this error - "ValueError: No JSON object could be decoded"  
=====

    import InstagramAPI

    username = 'username'
    password = 'password'
    debug = True
    i = InstagramAPI.Instagram(username,password,debug)
    recipients = ['friend1','friend2']
    text = "hello my friend!"
    photo = '/Users/mycomputer/Desktop/1.jpg'
    caption = 'Hello World!'

    i.direct_message(recipients, text)

======

    Proxy-Connection: keep-alive
    Connection: keep-alive
    Accept: */*
    Content-type: multipart/form-data boundary=a01bbb08-f2b6-4cfd-95dd-29a6c8b2b953
    Accept-Language: en-en
    Content-Length: 498
    
    * upload completely sent off: 498 out of 498 bytes
    < HTTP/1.1 400 Bad Request
    < Pragma: no-cache
    < Cache-Control: private, no-cache, no-store, must-revalidate
    < Vary: Cookie, Accept-Language
    < Content-Language: en
    < Expires: Sat, 01 Jan 2000 00:00:00 GMT
    < Date: Sun, 12 Mar 2017 03:26:30 GMT
    < Content-Type: text/html; charset=utf-8
    * Replaced cookie csrftoken="7jAdabE4pRi9jAmCauZPVJAf4SW8c7iO" for domain  i.instagram.com, path /, expire 1520738790
    < Set-Cookie: csrftoken=7jAdabE4pRi9jAmCauZPVJAf4SW8c7iO; expires=Sun, 11-Mar-2018 03:26:30 GMT; Max-Age=31449600; Path=/; Secure
    < Connection: keep-alive
    < Content-Length: 11
    < 
    * Connection #0 to host i.instagram.com left intact

    File "testdirectmessage.py", line 12, in <module>
        i.direct_message(recipients, text)
      File "/usr/local/lib/python2.7/site-packages/InstagramAPI/src/Instagram.py", line 440, in direct_message
        self.http.direct_message(recipients, text)
      File "/usr/local/lib/python2.7/site-packages/InstagramAPI/src/http/HttpInterface.py", line 575, in direct_message
        upload = json.loads(resp[header_len:])
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

**Comment by antonid08** [comment]
same error. get 
`400 - Bad Request`
in responce while debugging

**Comment by antonid08** [comment]
Hey, guys, are you here?

**Comment by danleyb2** [comment]
the recipients should be  usernameIDs not usernames, you can test with mine 446256538, :)

**Comment by kennychung** [comment]
Thank you! It is working. ;)

**Comment by antonid08** [comment]
still same error. maybe i use deprecated version? where i can get an actual?

UPD: sorry, i havent noticed the commit.
